Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/CommentIndentation:
  Exclude:
    - lib/union_station_hooks_core/request_reporter.rb

Lint/RescueException:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Lint/Eval:
  Exclude:
    - lib/union_station_hooks_core/version.rb

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 300

Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Max: 20
