Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 300

Metrics/ClassLength:
  Max: 300
