language: ruby
install:
  - gem install bundler --no-document
  - bundle install --jobs=3 --retry=3 --deployment --without notravis --with travis
  - bundle clean
cache:
  directories:
    - vendor/bundle
    - passenger
script: rake spec:travis
sudo: false
